name: Normalize Commit Authors (Smart)

on:
  push:
    branches:
      - main
      - dev
      - feature/**

permissions:
  contents: write

jobs:
  normalize-authors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git identity
        run: |
          git config user.name "gshubham804"
          git config user.email "gshubham804@gmail.com"

      - name: Prepare rebase script
        run: |
          cat > /tmp/rewrite-author.sh <<'EOF'
          #!/usr/bin/env bash
          if git diff-tree --no-commit-id --name-only -r HEAD | grep -q '^.github/workflows/'; then
            echo "Skipping workflow commit"
            exit 0
          fi

          AUTHOR_EMAIL=$(git show -s --format='%ae' HEAD)
          if [ "$AUTHOR_EMAIL" != "gshubham804@gmail.com" ]; then
            COMMIT_DATE=$(git show -s --format=%ci HEAD)
            if [ -z "$COMMIT_DATE" ]; then
              COMMIT_DATE=$(date -R)
            fi
            GIT_COMMITTER_DATE="$COMMIT_DATE" git commit --amend --no-edit \
              --author='gshubham804 <gshubham804@gmail.com>' --date "$COMMIT_DATE"
          fi
          EOF
          chmod +x /tmp/rewrite-author.sh

      - name: Rewrite authors
        run: |
          if [ "${{ github.event.before }}" = "0000000000000000000000000000000000000000" ]; then
            START=$(git rev-list --max-parents=0 HEAD)
          else
            START=${{ github.event.before }}
          fi

          git rebase -i --rebase-merges --exec "/tmp/rewrite-author.sh" "$START"^ --no-autostash

      - name: Force push rewritten branch
        run: git push --force
