name: Normalize Commit Authors (Smart)

on:
  push:
    branches:
      - main
      - dev
      - feature/**

permissions:
  contents: write

jobs:
  normalize-authors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git identity
        run: |
          git config user.name "gshubham804"
          git config user.email "gshubham804@gmail.com"

      - name: Rewrite authors only for new commits (skip workflow files)
        run: |
          if [ "${{ github.event.before }}" = "0000000000000000000000000000000000000000" ]; then
            RANGE=$(git rev-list --reverse HEAD)
          else
            RANGE=$(git rev-list --reverse ${{ github.event.before }}..HEAD)
          fi

          for commit in $RANGE; do
            # Skip commits that modify workflow files
            if git diff-tree --no-commit-id --name-only -r $commit | grep -q '^.github/workflows/'; then
              echo "Skipping $commit (workflow file changes)"
              continue
            fi

            AUTHOR_EMAIL=$(git show -s --format='%ae' $commit)

            if [ "$AUTHOR_EMAIL" != "gshubham804@gmail.com" ]; then
              COMMIT_DATE="$(git show -s --format=%ci $commit)"
              if [ -z "$COMMIT_DATE" ]; then
                COMMIT_DATE="$(date -R)"
              fi

              GIT_COMMITTER_DATE="$COMMIT_DATE" \
              git rebase --rebase-merges --onto $commit^ $commit \
                --exec "git commit --amend --no-edit --author='gshubham804 <gshubham804@gmail.com>' --date \"$COMMIT_DATE\""
            fi
          done

      - name: Force push rewritten branch
        run: git push --force
