name: Normalize Commit Authors (Filter-Repo, Range Limited)

on:
  push:
    branches:
      - main
      - dev
      - feature/**

permissions:
  contents: write

jobs:
  normalize-authors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install git-filter-repo
        run: |
          sudo apt-get update
          sudo apt-get install -y python3
          curl -s https://raw.githubusercontent.com/newren/git-filter-repo/main/git-filter-repo > /usr/local/bin/git-filter-repo
          chmod +x /usr/local/bin/git-filter-repo

      - name: Rewrite commit authors for recent push
        run: |
          # Get commit range from GitHub push event
          if [ "${{ github.event.before }}" = "0000000000000000000000000000000000000000" ]; then
            RANGE="HEAD"
          else
            RANGE="${{ github.event.before }}..HEAD"
          fi

          # Create a temporary branch with only the recent commits
          git checkout -b temp-rewrite
          git reset --hard ${{ github.event.before }}

          # Cherry-pick commits into a clean branch, rewriting author
          git checkout -b fixed-branch ${{ github.event.before }}
          for commit in $(git rev-list --reverse $RANGE); do
            AUTHOR_EMAIL=$(git show -s --format='%ae' "$commit")
            GIT_COMMITTER_DATE="$(git show -s --format=%ci $commit)"
            if [ "$AUTHOR_EMAIL" = "shubham.gupta@poxscan.io" ]; then
              git cherry-pick --allow-empty --keep-redundant-commits "$commit"
              git commit --amend --no-edit --author="gshubham804 <gshubham804@gmail.com>" --date "$GIT_COMMITTER_DATE"
            else
              git cherry-pick --allow-empty --keep-redundant-commits "$commit"
            fi
          done

          git branch -M fixed-branch main

      - name: Force push rewritten branch
        run: git push --force
